/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#72ff70",
        "secondary-fixed": "#8afb83",
        "tertiary-fixed": "#ffdcbd",
        "surface-container-low": "#1c1b1b",
        "background": "#131313",
        "on-primary-fixed": "#002203",
        "on-background": "#e5e2e1",
        "on-surface-variant": "#b9ccb2",
        "on-tertiary-fixed-variant": "#5d4124",
        "surface-dim": "#131313",
        "surface-tint": "#00e639",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "surface-container-highest": "#353534",
        "secondary-fixed-dim": "#6ede69",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#003907",
        "inverse-primary": "#006e16",
        "secondary-container": "#01881e",
        "surface": "#131313",
        "primary-container": "#00ff41",
        "on-primary-container": "#007117",
        "inverse-surface": "#e5e2e1",
        "primary": "#ebffe2",
        "tertiary-container": "#ffd5ae",
        "tertiary": "#fff8f4",
        "inverse-on-surface": "#313030",
        "secondary": "#6ede69",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed": "#002203",
        "outline": "#84967e",
        "primary-fixed-dim": "#00e639",
        "tertiary-fixed-dim": "#e7bf99",
        "on-primary": "#003907",
        "surface-variant": "#353534",
        "on-tertiary-fixed": "#2c1701",
        "on-secondary-fixed-variant": "#00530e",
        "surface-bright": "#3a3939",
        "on-primary-fixed-variant": "#00530e",
        "outline-variant": "#3b4b37",
        "on-error": "#690005",
        "on-tertiary": "#442b10",
        "on-tertiary-container": "#7a5b3c",
        "on-secondary-container": "#f7fff0",
        "error": "#ffb4ab"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px"
      },
    },
  },
  plugins: [],
}